Add another example for ddns-service
I kept getting the following error and couldn't figure out why.
  HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/home/node/app/node_modules/got/dist/source/as-promise.js:118:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Turns out it was a error from my side (of course) for looking mostly at
examples and not properly reading the usage. I inserted the entry name
together with the domain name, i.e. --domainName="foo.example.nl", which
of course should be --domainName="example.nl" --name="foo".

This commit is for users like me, may it save them some time.